# Generated by Django 6.0.5 on 2026-05-30 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_team_size_friendrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['round_number', 'match_order']},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='match',
            name='match_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Регистрация до'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='is_accepted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('registration', '📢 Регистрация открыта'), ('in_progress', '⚔️ Идёт турнир'), ('finished', '🏆 Завершён')], db_index=True, default='registration', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['from_user', 'to_user', 'is_accepted'], name='idx_friendreq_users_accepted'),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['to_user', 'is_accepted'], name='idx_friendreq_to_accepted'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'round_number', 'match_order'], name='idx_match_tourn_round_order'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['captain'], name='idx_team_captain'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['status', '-created_at'], name='idx_tournament_status_created'),
        ),
    ]
